version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app:ro
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env
